<div class="report-print-header is-visible">
  <img src="../../../../../company_logo.png" alt="Natura Crop Care" class="report-logo">
  <div class="report-header-text">
    <h2>Natura Crop Care</h2>
    <p class="report-subtitle"><?= htmlspecialchars($reportTitle) ?></p>
    <p class="report-meta"><?= htmlspecialchars(implode(" \xC2\xB7 ", $filterParts)) ?></p>
    <p class="report-meta">Generated by <?= htmlspecialchars($generatedBy) ?> on <?= htmlspecialchars($generatedOn) ?></p>
  </div>
</div>
